In [4]:
import numpy as np
from numpy import genfromtxt
import pandas as pd

In [15]:
data = genfromtxt('bank_note_data.txt',delimiter=',')

In [16]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [22]:
labels = data[:,4]

In [23]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [24]:
features = data[:,0:4]

In [25]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [26]:
X = features
y = labels


In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [31]:
from sklearn.preprocessing import MinMaxScaler

In [32]:
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [33]:
scaled_X_train = scaler_object.transform(X_train)

In [34]:
scaled_X_test = scaler_object.transform(X_test)

In [35]:
scaled_X_train.max()

1.0000000000000002

In [36]:
scaled_X_train.min()

0.0

In [37]:
from keras.models import Sequential
from keras.layers import Dense

In [38]:
model= Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8, activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [39]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [42]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.3248 - accuracy: 0.8781
Epoch 2/50
 - 0s - loss: 0.3119 - accuracy: 0.8836
Epoch 3/50
 - 0s - loss: 0.2993 - accuracy: 0.8923
Epoch 4/50
 - 0s - loss: 0.2875 - accuracy: 0.9042
Epoch 5/50
 - 0s - loss: 0.2753 - accuracy: 0.9086
Epoch 6/50
 - 0s - loss: 0.2637 - accuracy: 0.9151
Epoch 7/50
 - 0s - loss: 0.2526 - accuracy: 0.9206
Epoch 8/50
 - 0s - loss: 0.2424 - accuracy: 0.9282
Epoch 9/50
 - 0s - loss: 0.2321 - accuracy: 0.9314
Epoch 10/50
 - 0s - loss: 0.2215 - accuracy: 0.9391
Epoch 11/50
 - 0s - loss: 0.2130 - accuracy: 0.9445
Epoch 12/50
 - 0s - loss: 0.2037 - accuracy: 0.9402
Epoch 13/50
 - 0s - loss: 0.1954 - accuracy: 0.9445
Epoch 14/50
 - 0s - loss: 0.1889 - accuracy: 0.9434
Epoch 15/50
 - 0s - loss: 0.1811 - accuracy: 0.9521
Epoch 16/50
 - 0s - loss: 0.1734 - accuracy: 0.9543
Epoch 17/50
 - 0s - loss: 0.1668 - accuracy: 0.9532
Epoch 18/50
 - 0s - loss: 0.1607 - accuracy: 0.9565
Epoch 19/50
 - 0s - loss: 0.1551 - accuracy: 0.9597
Epoch 20/50
 - 0s - l

In [43]:
predictions = model.predict_classes(scaled_X_test)

In [45]:
model.metrics_names

['loss', 'accuracy']

In [46]:
from sklearn.metrics import confusion_matrix, classification_report

In [47]:
confusion_matrix(y_test,predictions)

array([[251,   6],
       [  7, 189]])

In [48]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.97      0.98      0.97       257
         1.0       0.97      0.96      0.97       196

    accuracy                           0.97       453
   macro avg       0.97      0.97      0.97       453
weighted avg       0.97      0.97      0.97       453



In [49]:
model.save('my-first-keras-model.h5')

In [50]:
from keras.models import load_model

In [51]:
revived_model = load_model('my-first-keras-model.h5')

In [52]:
revived_model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    